// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class LivroListaComponent implements OnInit {
  editoras: Editora[] = [];
  livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit() {
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir = (codigo?: string) => {
    if (!codigo) return;
    this.servLivros
      .excluir(codigo)
      .then(() => this.servLivros.obterLivros())
      .then((livros) => (this.livros = livros));
  };

  obterNome = (codEditora?: number) => {
    if (!codEditora) return;
    this.servEditora.getNomeEditora(codEditora);
  };
}

<h1>Catálogo de Livros</h1>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Resumo</th>
      <th scope="col">Editora</th>
      <th scope="col">Autores</th>
      <th></th>
    </tr>
  </thead>
  <tbody className="table-group-divider">
    <tr *ngFor="let livro of livros">
      <td>{{ livro.titulo }}</td>
      <td>{{ livro.resumo }}</td>
      <td>{{ obterNome(livro.codEditora) }}</td>
      <td>
        <ul>
          <li *ngFor="let autor of livro.autores">{{ autor }}</li>
        </ul>
      </td>
      <td>
        <button
          type="button"
          (click)="excluir(livro.codigo)"
          class="btn btn-danger"
        >
          Excluir
        </button>
      </td>
    </tr>
  </tbody>
</table>

// clientes/livros-react/src/LivroLista.tsx
import { FC, useEffect, useState } from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { Livro } from "./modelo/Livro";
import { ControleEditora } from "./controle/ControleEditora";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro: FC<{ livro: Livro; excluir: (codigo?: string) => void }> = ({
  livro,
  excluir,
}) => {
  return (
    <tr>
      <td>{livro.titulo}</td>
      <td>{livro.resumo}</td>
      <td>{controleEditora.getNomeEditora(livro.codEditora)}</td>
      <td>
        <ul>
          {livro.autores?.map((autor, i) => (
            <li key={i}>{autor}</li>
          ))}
        </ul>
      </td>
      <td>
        <button
          type="button"
          onClick={() => excluir(livro.codigo)}
          className="btn btn-danger"
        >
          Excluir
        </button>
      </td>
    </tr>
  );
};

export const LivroLista: FC<{}> = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    controleLivro.obterLivros().then((livros) => {
      setLivros(livros);
      setCarregado(true);
    })
  }, [carregado]);

  const excluir = (codigo?: string) => {
    if(!codigo) return;
    controleLivro.excluir(codigo).then(() => setCarregado(false));
  };

  return (
    <main>
      <h1>Catálogo de Livros</h1>
      <table className="table table-striped">
        <thead className="table-dark">
          <tr>
            <th scope="col">Título</th>
            <th scope="col">Resumo</th>
            <th scope="col">Editora</th>
            <th scope="col">Autores</th>
            <th></th>
          </tr>
        </thead>
        <tbody className="table-group-divider">
          {livros.map((livro, index) => (
            <LinhaLivro livro={livro} excluir={excluir} key={index} />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;
