// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule, NgFor } from '@angular/common';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
  standalone: true,
  imports: [CommonModule, FormsModule],
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro();
  autoresForm: string = '';
  editoras: Editora[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    const editora = this.editoras.at(0)?.codEditora;
    if (!editora) return;
    this.livro.codEditora = editora;
  }

  incluir = () => {
    const updatedLivro: Livro = {
      ...this.livro,
      autores: this.autoresForm.split(/\r?\n|\r|\n/g),
    };
    this.servLivros
      .incluir(updatedLivro)
      .then(() => this.router.navigateByUrl('/lista'));
  };
}

<h1>Dados do Livro</h1>

<form (submit)="incluir()" ngNativeValidate>
  <div class="mb-3">
    <label class="form-label">Título</label>
    <input class="form-control" name="titulo" [(ngModel)]="livro.titulo" required />
  </div>
  <div class="mb-3">
    <label class="form-label" required>Resumo</label>
    <textarea
      class="form-control"
      name="resumo"
      [rows]="3"
      [(ngModel)]="livro.resumo"
      required
    ></textarea>
  </div>
  <div class="mb-3">
    <label class="form-label">Editora</label>
    <select class="form-control" name="codEditora" [(ngModel)]="livro.codEditora" required>
      <option *ngFor="let editora of editoras" [value]="editora.codEditora">
        {{ editora.nome }}
      </option>
    </select>
  </div>
  <div class="mb-3">
    <label class="form-label">Autores (1 por linha)</label>
    <textarea
      class="form-control"
      name="autoresForm"
      [rows]="3"
      [(ngModel)]="autoresForm"
      required
    ></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Salvar Dados</button>
</form>

// clientes/livros-react/src/LivroDados.tsx
import { ChangeEvent, FC, FormEvent, useState } from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";
import { Livro } from "./modelo/Livro";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

export const LivroDados: FC = () => {
  const opcoes = controleEditora
    .getEditoras()
    .map((editora) => ({ value: editora.codEditora, text: editora.nome }));
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0].value);
  const navigate = useNavigate();

  const tratarCombo = (e: ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(e.target.value));
  };

  const incluir = (e: FormEvent) => {
    e.preventDefault();
    const livro = new Livro(
      '',
      codEditora!,
      titulo,
      resumo,
      autores.split(/\r?\n|\r|\n/g)
    );
    controleLivro.incluir(livro).then(() => navigate("/"));
  };

  return (
    <>
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className="mb-3">
          <label className="form-label">Título</label>
          <input
            className="form-control"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
          />
        </div>
        <div className="mb-3">
          <label className="form-label">Resumo</label>
          <textarea
            className="form-control"
            rows={3}
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
          ></textarea>
        </div>
        <div className="mb-3">
          <label className="form-label">Editora</label>
          <select
            className="form-control"
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((editora) => <option key={editora.value} value={editora.value}>{editora.text}</option>)}
          </select>
        </div>
        <div className="mb-3">
          <label className="form-label">Autores (1 por linha)</label>
          <textarea
            className="form-control"
            rows={3}
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
          ></textarea>
        </div>
        <button type="submit" className="btn btn-primary">Salvar Dados</button>
      </form>
    </>
  );
};

export default LivroDados;
